# Generated by Django 2.1.7 on 2019-03-24 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografy', models.TextField(blank=True, max_length=300, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('social_network_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_network', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAddress',
            fields=[
                ('type_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserSocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=200, null=True, unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=300)),
                ('social_network_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='accounts.SocialNetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('latitud', models.CharField(blank=True, max_length=150, null=True)),
                ('longitud', models.CharField(blank=True, max_length=150, null=True)),
                ('type_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_documents', to='accounts.TypeAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
