# Generated by Django 2.1.7 on 2019-03-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialnetwork',
            old_name='social_network_id',
            new_name='social_network',
        ),
        migrations.RenameField(
            model_name='usertypeaddress',
            old_name='type_address_id',
            new_name='type_address',
        ),
    ]
