# Generated by Django 2.1.7 on 2019-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_document',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Number document'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_document',
            field=models.CharField(choices=[('D', 'DNI'), ('P', 'Pasaporte'), ('C', 'Carnet de extrajeria')], db_index=True, max_length=1, null=True, verbose_name='Type document'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_register',
            field=models.CharField(choices=[('C', 'Correo'), ('F', 'Facebook'), ('T', 'Twitter'), ('I', 'Instagram'), ('G', 'Gmail')], db_index=True, max_length=1, null=True, verbose_name='Type register'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biografy',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Biografry'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
    ]
