# Generated by Django 2.1.7 on 2019-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190326_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameId',
            fields=[
                ('username_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
