# Generated by Django 2.1.7 on 2019-03-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190324_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialnetwork',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usersocialnetwork',
            name='first_name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='usersocialnetwork',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
