# Generated by Django 2.1.7 on 2019-03-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usernameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialnetwork',
            name='social_network',
            field=models.CharField(choices=[('C', 'Correo'), ('F', 'Facebook'), ('T', 'Twitter'), ('I', 'Instagram'), ('G', 'Gmail')], db_index=True, default='C', max_length=1, verbose_name='Type register'),
        ),
    ]
