# Generated by Django 2.1.7 on 2019-03-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190324_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.AddField(
            model_name='usersocialnetwork',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
