# Generated by Django 2.1.7 on 2019-03-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190326_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type_register',
        ),
        migrations.AddField(
            model_name='user',
            name='type_register',
            field=models.CharField(choices=[('C', 'Correo'), ('F', 'Facebook'), ('T', 'Twitter'), ('I', 'Instagram'), ('G', 'Gmail')], db_index=True, default='C', max_length=1, verbose_name='Type register'),
        ),
    ]
