# Generated by Django 2.1.7 on 2019-04-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190326_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_register',
            field=models.CharField(choices=[('correo', 'Correo'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('gmail', 'Gmail')], db_index=True, default='correo', max_length=15, verbose_name='Type register'),
        ),
        migrations.AlterField(
            model_name='usersocialnetwork',
            name='social_network',
            field=models.CharField(choices=[('correo', 'Correo'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('gmail', 'Gmail')], db_index=True, default='correo', max_length=15, verbose_name='Type register'),
        ),
    ]
